[package]
name = "pcli"
version = "1.6.11"
edition = "2021"
authors = ["Julian Chultarsky <jchultarsky@physna.com>"]
description = "CLI client utility to the Physna public API/V2"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
futures = "0.3"
clap = { version = "3.2", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking", "multipart", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
serde_path_to_error = "0.1"
tokio = { version = "1.19", features = ["full"] }
http = "0.2"
base64 = "0.13"
#openapi = { path = "../api-client-v2" }
dirs = "4.0"
jwt = "0.16"
hmac = "0.12"
sha2 = "0.10"
jsonwebtoken = "8.1"
rpassword = "6.0"
indicatif = { version = "0.16", features = ["rayon"] }
csv = "1.1.6"
claim = "0.5"
anyhow = "1.0"
thiserror = "1.0"
#html-builder = "0.4"
uuid = { version = "1.1", features = ["v4", "serde"] }
colored = "2.0"
ptree = "0.4"
cached = "0.34"
matrix = "0.22"
indexmap = "1.9"
petgraph = { version = "0.6", features = ["matrix_graph"] }
exitcode = "1.1"
url = "^2.2"
substring = "1.4"
unicase = "2.6"
sysinfo = "0.24"
glob = "0.3"
