[package]
name = "pcli"
version = "1.8.7"
edition = "2021"
authors = ["Julian Chultarsky <jchultarsky@physna.com>"]
description = "CLI client utility to the Physna public API/V2"

[[bin]]
name = "pcli"

[dependencies]
log = "0.4.17"
pretty_env_logger = "0.4.0"
futures = "0.3.28"
clap = { version = "4.2.5", features = ["derive"] }
reqwest = { version = "0.11.18", features = ["blocking", "multipart", "json", "stream"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_yaml = "0.9.21"
serde_json = "1.0.96"
serde_path_to_error = "0.1.11"
tokio = { version = "1.28.0", features = ["full"] }
http = "0.2.9"
base64 = "0.21.0"
#openapi = { path = "../api-client-v2" }
dirs = "5.0.0"
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.6"
jsonwebtoken = "8.3.0"
rpassword = "7.2.0"
indicatif = { version = "0.17.3", features = ["rayon"] }
csv = "1.2.1"
#claim = "0.5.0"
anyhow = "1.0.70"
thiserror = "1.0.40"
#html-builder = "0.4"
uuid = { version = "1.3.1", features = ["v4", "serde"] }
colored = "2.0.0"
ptree = "0.4.0"
cached = "0.43.0"
matrix = "0.22.0"
indexmap = "1.9.3"
petgraph = { version = "0.6.3", features = ["matrix_graph"] }
exitcode = "1.1.2"
url = "2.3.1"
substring = "1.4.5"
unicase = "2.6.0"
sysinfo = "0.28.4"
glob = "0.3.1"
serde_with = "2.1.0"
ntapi = "0.4.1"
